Run smoker verbose to get full diffs
Without this, the diffs get shortened which makes them hard to use:

    AssertionError: Error messages with log level SEVERE in browser console assert ['https://pip...con' of null"] == []   Left contains 2 more items, first extra item: 'https://pipeline-foreman-server-nightly-centos7.n59.example.com/webpack/foreman-vendor.bundle-v4.0.7-production-ed656...rver-nightly-centos7.n59.example.com/webpack/foreman-vendor.bundle-v4.0.7-production-ed656fd12ee634eae9b9.js:329:3878)'   Use -v to get the full diff

The diffs can be quite large so -vv needs to be used instead of just -v.
Note that junit.xml is also truncated so it must be set.